name: Deploy Add Goal Rules

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Add GoalRules
      - name: Add Goal rules
        run: cd goal-rules/add/; GOOS=linux go build cmd/main.go; zip addGoalRules.zip main; ls;

      - name: Add GoalRules Test
        run: cd goal-rules/add/; go test -v ./...
        
      - name: Add addGoalRules gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  addGoalRules --zip-file fileb://goal-rules/add/addGoalRules.zip
