name: Deploy Add Tag

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add Tag
      - name: Add tag
        run: cd tag/add/; GOOS=linux go build cmd/main.go; zip addTag.zip main; ls;

      - name: Add Tag Test
        run: cd tag/add/; go test -v ./...

      - name: Add Tag gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addTag
          zip_file: tag/add/addTag.zip
