name: Deploy Add Transaction

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add Transaction
      - name: Add transaction
        run: cd transaction/add/; GOOS=linux go build cmd/main.go; zip addTransaction.zip main; ls;

      #- name: Add Transaction Test
      #  run: cd transaction/add/; go test -v ./...

      - name: Add Transaction gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addTransaction
          zip_file: transaction/add/addTransaction.zip
