name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add Goal
      - name: Add goal
        run: cd goal/add/; GOOS=linux go build cmd/main.go; zip addGoal.zip main;

      - name: Add Goal Test
        run: cd goal/add/; go test -v ./...

      - name: Add Goal gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addGoal
          zip_file: cd goal/add/build/addGoal.zip
