name: Deploy Add Investment 

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Add Investment
      - name: Add Investment
        run: cd investment/add/; GOOS=linux go build cmd/main.go; zip addInvestment.zip main; ls;

      - name: Add Investment Test
        run: cd investment/add/; go test -v ./...
        
      - name: Add Investment gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  addInvestment --zip-file fileb://investment/add/addInvestment.zip
  