name: Deploy Add Budget

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      # Add Budget
      - name: Add budget
        run: cd budget/add/; GOOS=linux go build cmd/main.go; zip addBudget.zip main; ls;

      - name: Add Budget Test
        run: cd budget/add/; go test -v ./...

      - name: Add Budget gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  addBudget --zip-file fileb://budget/add/addBudget.zip
  
