name: Deploy Add Debt

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add Debt
      - name: Add debt
        run: cd debt/add/; GOOS=linux go build cmd/main.go; zip addDebt.zip main; ls;

      - name: Add Debt Test
        run: cd debt/add/; go test -v ./...

      - name: Add Debt gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addDebt
          zip_file: debt/add/addDebt.zip
