name: Deploy Add Debt Rules

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add DebtRules
      - name: Add Debt rules
        run: cd debt-rules/add/; GOOS=linux go build cmd/main.go; zip addDebtRules.zip main; ls;

      #- name: Add DebtRules Test
      #  run: cd debt-rules/add/; go test -v ./...

      - name: Add DebtRules gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addDebtRules
          zip_file: debt-rules/add/addDebtRules.zip
