name: Deploy Add Investment Rules

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add InvestmentRules
      - name: Add rules
        run: cd investment-rules/add/; GOOS=linux go build cmd/main.go; zip addInvestmentRules.zip main; ls;

      #- name: Add InvestmentRules Test
      #  run: cd investment-rules/add/; go test -v ./...

      - name: Add InvestmentRules gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addInvestmentRules
          zip_file: investment-rules/add/addInvestmentRules.zip
