name: Deploy Add Transaction

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Add Transaction
      - name: Add transaction
        run: cd transactions/add/; GOOS=linux go build cmd/main.go; zip addTransaction.zip main; ls;

      - name: Add Transaction Test
        run: cd transactions/add/; go test -v ./...
        
      - name: Add addTransactions gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  addTransactions --zip-file fileb://transactions/add/addTransaction.zip
