name: Deploy Add Category

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add Category
      - name: Add category
        run: cd category/add/; GOOS=linux go build cmd/main.go; zip addCategory.zip main; pwd;

      #- name: Add Category Test
      #  run: cd category/add/; go test -v ./...

      - name: Add Category gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addCategory
          zip_file: cd category/add/addCategory.zip
