name: Deploy Add Goal

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Add Goal
      - name: Add goal
        run: cd goals/add/; GOOS=linux go build cmd/main.go; zip addGoal.zip main; ls;

      - name: Add Goal Test
        run: cd goals/add/; go test -v ./...
          
      - name: Add Goal gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  addGoals --zip-file fileb://goals/add/addGoal.zip
