name: Deploy Add Notification 

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add Notification
      - name: Add notifications
        run: cd notifications/add/; GOOS=linux go build cmd/main.go; zip addNotification.zip main; ls;

      - name: Add Notification Test
        run: cd notifications/add/; go test -v ./...

      - name: Add Notification gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addNotification
          zip_file: notifications/add/addNotification.zip
