name: Deploy Add GoalLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Add GoalLinkTrigger
      - name: Add dynamodb-stream/goal-link-trigger
        run: cd dynamodb-stream/goal-link-trigger/add/; GOOS=linux go build cmd/main.go; zip addGoalLinkTrigger.zip main; ls;

      - name: Add GoalLinkTrigger Test
        run: cd dynamodb-stream/goal-link-trigger/add/; go test -v ./...
          
      - name: Add addGoalLinkTrigger gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  addGoalLinkTrigger --zip-file fileb://dynamodb-stream/goal-link-trigger/add/addGoalLinkTrigger.zip
