name: Deploy Add InvestmentLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add InvestmentLinkTrigger
      - name: Add dynamodb-stream/investment-link-trigger
        run: cd dynamodb-stream/investment-link-trigger/add/; GOOS=linux go build cmd/main.go; zip addInvestmentLinkTrigger.zip main; ls;

      #- name: Add InvestmentLinkTrigger Test
      #  run: cd dynamodb-stream/investment-link-trigger/add/; go test -v ./...

      - name: Add InvestmentLinkTrigger gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: addInvestmentLinkTrigger
          zip_file: dynamodb-stream/investment-link-trigger/add/addInvestmentLinkTrigger.zip
