name: Deploy Batch Get Category

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Get Category
      - name: Get category
        run: cd category/batch-get/; GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build cmd/main.go; zip batchGetCategory.zip main; ls;

      - name: Get Category Test
        run: cd category/batch-get/; go test -v ./...
          
      - name: Add batchGetCategoryItems gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  batchGetCategoryItems --zip-file fileb://category/batch-get/batchGetCategory.zip
