name: Deploy Delete CategoryLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Remove CategoryLinkTrigger
      - name: Remove dynamodb-stream/category-link-trigger
        run: cd dynamodb-stream/category-link-trigger/delete/; GOOS=linux go build cmd/main.go; zip deleteCategoryLinkTrigger.zip main; ls;

      - name: Remove CategoryLinkTrigger Test
        run: cd dynamodb-stream/category-link-trigger/delete/; go test -v ./...

      - name: Remove CategoryLinkTrigger gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: deleteCategoryLinkTrigger
          zip_file: dynamodb-stream/category-link-trigger/delete/deleteCategoryLinkTrigger.zip