name: Deploy Patch DeleteOneItem

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch DeleteOneItem
      - name: Patch deleteOneItem
        run: cd delete/delete-one-item/; GOOS=linux go build cmd/main.go; zip deleteOneItem.zip main; ls;

      #- name: Patch DeleteOneItem Test
      # run: cd delete/delete-one-item/; go test -v ./...

      - name: Patch DeleteOneItem gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: deleteOneItem
          zip_file: delete/delete-one-item/deleteOneItem.zip
