name: Deploy Get Category

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Get Category
      - name: Get category
        run: cd category/get/; GOOS=linux go build cmd/main.go; zip getCategory.zip main; ls;

      - name: Get Category Test
        run: cd category/get/; go test -v ./...

      - name: Get Category gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getCategory
          zip_file: category/get/getCategory.zip
