name: Deploy Get Wallet

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Get Wallet
      - name: Get wallet
        run: cd wallet/get/; GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build cmd/main.go; zip getWallet.zip main; ls;

      - name: Get Wallet Test
        run: cd wallet/get/; go test -v ./...

      - name: Add getWallet gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  getWallet --zip-file fileb://wallet/get/getWallet.zip
