name: Deploy Get Goal

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Get Goal
      - name: Get goal
        run: cd goals/get/; GOOS=linux go build cmd/main.go; zip getGoal.zip main; ls;

      - name: Get Goal Test
        run: cd goals/get/; go test -v ./...

      - name: Get Goal gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getGoals
          zip_file: goals/get/getGoal.zip
