name: Deploy Get Notification

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Get Notifications
      - name: Get notification
        run: cd notifications/get/; GOOS=linux go build cmd/main.go; zip getNotification.zip main; ls;

      #- name: Get Notification Test
      #  run: cd notifications/get/; go test -v ./...

      - name: Get Notification gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getNotification
          zip_file: notifications/get/getNotification.zip
