name: Deploy Get Debt

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Get Debt
      - name: Get debt
        run: cd debt/get/; GOOS=linux go build cmd/main.go; zip getDebt.zip main; ls;

      #- name: Get Debt Test
      #  run: cd debts/get/; go test -v ./...

      - name: Get Debt gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getDebt
          zip_file: debt/get/getDebt.zip
