name: Deploy Get Investment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Get Investment
      - name: Get investment
        run: cd investment/get/; GOOS=linux go build cmd/main.go; zip getInvestment.zip main; ls;

      - name: Get Investment Test
        run: cd investment/get/; go test -v ./...

      - name: Get Investment gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getInvestment
          zip_file: investment/get/getInvestment.zip
