name: Deploy Get Budget

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Get Budget
      - name: Get budget
        run: cd budget/get/; GOOS=linux go build cmd/main.go; zip getBudget.zip main;

      - name: Get Budget Test
        run: cd budget/get/; go test -v ./...

      - name: Get Budget gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getBudget
          zip_file: cd budget/get/build/getBudget.zip
