name: Deploy Get Transaction

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Get Transaction
      - name: Get transaction
        run: cd transaction/get/; GOOS=linux go build cmd/main.go; zip getTransaction.zip main;

      #- name: Get Transaction Test
      #  run: cd transaction/get/; go test -v ./...

      - name: Get Transaction gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getTransaction
          zip_file: cd transaction/get/build/getTransaction.zip
