name: Deploy Get Investment Rules

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Get InvestmentRules
      - name: Get investment-rules
        run: cd investment-rules/get/; GOOS=linux go build cmd/main.go; zip getInvestmentRules.zip main; ls;

      - name: Get InvestmentRules Test
        run: cd investment-rules/get/; go test -v ./...

      - name: Add getInvestmentRules gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  getInvestmentRules --zip-file fileb://investment-rules/get/getInvestmentRules.zip
