name: Deploy Get Investment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Get Investment
      - name: Get investment
        run: cd investment/get/; GOOS=linux go build cmd/main.go; zip getInvestment.zip main; ls;

      - name: Get Investment Test
        run: cd investment/get/; go test -v ./...

      - name: Add getInvestment gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  getInvestment --zip-file fileb://investment/get/getInvestment.zip
