name: Deploy Get Debt

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Get Debt
      - name: Get debt
        run: cd debt/get/; GOOS=linux go build cmd/main.go; zip getDebt.zip main; ls;

      - name: Get Debt Test
        run: cd debt/get/; go test -v ./...

      - name: Add getDebt gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  getDebt --zip-file fileb://debt/get/getDebt.zip
