name: Deploy Get Goal Rules

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Get GoalRules
      - name: Get goal-rules
        run: cd goal-rules/get/; GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build cmd/main.go; zip getGoalRules.zip main; ls;

      - name: Get GoalRules Test
        run: cd goal-rules/get/; go test -v ./...

      - name: Add getGoalRules gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  getGoalRules --zip-file fileb://goal-rules/get/getGoalRules.zip
