name: Deploy Get Goal

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Get Goal
      - name: Get goal
        run: cd goals/get/; GOOS=linux go build cmd/main.go; zip getGoal.zip main; ls;

      - name: Get Goal Test
        run: cd goals/get/; go test -v ./...

      - name: Add getGoals gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  getGoals --zip-file fileb://goals/get/getGoal.zip
