name: Deploy Get Tag

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Get Tag
      - name: Get tag
        run: cd tag/get/; GOOS=linux go build cmd/main.go; zip getTag.zip main; ls;

      - name: Get Tag Test
        run: cd tag/get/; go test -v ./...

      - name: Get Tag gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: getTag
          zip_file: tag/get/getTag.zip
