name: Deploy Overview

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Overview
      - name: Get overview
        run: cd overview/; GOOS=linux go build cmd/main.go; zip overview.zip main; pwd;

      #- name: Overview Test
      #  run: cd overview/; go test -v ./...

      - name: Overview gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: overview
          zip_file: cd overview/build/overview.zip
