name: Deploy Patch GoalRules

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch GoalRules
      - name: Patch goal-rules
        run: cd goal-rules/update/; GOOS=linux go build cmd/main.go; zip patchGoalRules.zip main; ls;

      #- name: Patch GoalRules Test
      #  run: cd goal-rules/update/; go test -v ./...

      - name: Patch GoalRules gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchGoalRules
          zip_file: goal-rules/update/patchGoalRules.zip
