name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch Goal
      - name: Patch goal
        run: cd goal/update/; GOOS=linux go build cmd/main.go; zip patchGoal.zip main;

      - name: Patch Goal Test
        run: cd goal/update/; go test -v ./...

      - name: Patch Goal gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchGoal
          zip_file: cd goal/update/build/patchGoal.zip
