name: Deploy Patch Transaction

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch Transaction
      - name: Patch transaction
        run: cd transaction/update/; GOOS=linux go build cmd/main.go; zip patchTransaction.zip main;

      #- name: Patch Transaction Test
      #  run: cd transaction/update/; go test -v ./...

      - name: Patch Transaction gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchTransaction
          zip_file: cd transaction/update/build/patchTransaction.zip
