name: Deploy Patch Investment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch Investment
      - name: Patch investment
        run: cd investment/update/; GOOS=linux go build cmd/main.go; zip patchInvestment.zip main; ls;

      - name: Patch Investment Test
        run: cd investment/update/; go test -v ./...

      - name: Patch Investment gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchInvestment
          zip_file: investment/update/patchInvestment.zip
