name: Deploy Patch Investment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Patch Investment
      - name: Patch investment
        run: cd investment/update/; GOOS=linux go build cmd/main.go; zip patchInvestment.zip main; ls;

      - name: Patch Investment Test
        run: cd investment/update/; go test -v ./...

      - name: Add patchInvestment gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  patchInvestment --zip-file fileb://investment/update/patchInvestment.zip
