name: Deploy Patch Budget

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch Budget
      - name: Patch budget
        run: cd budget/update/; GOOS=linux go build cmd/main.go; zip patchBudget.zip main; ls;

      #- name: Patch Budget Test
      # run: cd budget/update/; go test -v ./...

      - name: Patch Budget gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchBudget
          zip_file: cd budget/update/patchBudget.zip
