name: Deploy Patch Tag

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch Tag
      - name: Patch tag
        run: cd tag/update/; GOOS=linux go build cmd/main.go; zip patchTag.zip main; ls;

      - name: Patch Tag Test
        run: cd tag/update/; go test -v ./...

      - name: Patch Tag gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchTag
          zip_file: tag/update/patchTag.zip
