name: Deploy Patch Budget

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Patch Budget
      - name: Patch budget
        run: cd budget/update/; GOOS=linux go build cmd/main.go; zip patchBudget.zip main; ls;

      - name: Patch Budget Test
        run: cd budget/update/; go test -v ./...

      - name: Add patchBudget gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  patchBudget --zip-file fileb://budget/update/patchBudget.zip
