name: Deploy Patch Category

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Patch Category
      - name: Patch category
        run: cd category/update/; GOOS=linux go build cmd/main.go; zip patchCategory.zip main; ls;

      - name: Patch Category Test
        run: cd category/update/; go test -v ./...

      - name: Add patchCategory gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  patchCategory --zip-file fileb://category/update/patchCategory.zip
