name: Deploy Patch Wallet

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Patch Wallet
      - name: Patch wallet
        run: cd wallet/update/; GOOS=linux go build cmd/main.go; zip patchWallet.zip main; ls;

      - name: Patch Wallet Test
        run: cd wallet/update/; go test -v ./...

      - name: Add patchWallet gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  patchWallet --zip-file fileb://wallet/update/patchWallet.zip
