name: Deploy Patch CategoryRules

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch CategoryRules
      - name: Patch category-rules
        run: cd category-rules/update/; GOOS=linux go build cmd/main.go; zip patchCategoryRules.zip main; ls;

      #- name: Patch CategoryRules Test
      #  run: cd category-rules/update/; go test -v ./...

      - name: Patch CategoryRules gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchCategoryRules
          zip_file: category-rules/update/patchCategoryRules.zip
