name: Deploy Patch Debt

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Patch Debt
      - name: Patch debt
        run: cd debt/update/; GOOS=linux go build cmd/main.go; zip patchDebt.zip main; ls;

      - name: Patch Debt Test
        run: cd debt/update/; go test -v ./...

      - name: Add patchDebt gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  patchDebt --zip-file fileb://debt/update/patchDebt.zip
