name: Deploy Patch InvestmentRules

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Patch InvestmentRules
      - name: Patch investment-rules
        run: cd investment-rules/update/; GOOS=linux go build cmd/main.go; zip patchInvestmentRules.zip main; ls;

      #- name: Patch InvestmentRules Test
      #  run: cd investment-rules/update/; go test -v ./...

      - name: Patch InvestmentRules gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: patchInvestmentRules
          zip_file: investment-rules/update/patchInvestmentRules.zip
