name: Deploy Add DebtLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Add DebtLinkTrigger
      - name: Add dynamodb-stream/debt-link-trigger
        run: cd dynamodb-stream/debt-link-trigger/remove/; GOOS=linux go build cmd/main.go; zip removeDebtLinkTrigger.zip main; ls;

      #- name: Add DebtLinkTrigger Test
      #  run: cd dynamodb-stream/debt-link-trigger/remove/; go test -v ./...

      - name: Add DebtLinkTrigger gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: removeDebtLinkTrigger
          zip_file: dynamodb-stream/debt-link-trigger/remove/removeDebtLinkTrigger.zip