name: Deploy Remove GoalLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Remove GoalLinkTrigger
      - name: Remove dynamodb-stream/goal-link-trigger
        run: cd dynamodb-stream/goal-link-trigger/remove/; GOOS=linux go build cmd/main.go; zip removeGoalLinkTrigger.zip main; ls;

      - name: Remove GoalLinkTrigger Test
        run: cd dynamodb-stream/goal-link-trigger/remove/; go test -v ./...

      - name: Add removeGoalLink gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  removeGoalLink --zip-file fileb://dynamodb-stream/goal-link-trigger/remove/removeGoalLinkTrigger.zip