name: Deploy Remove GoalLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Remove GoalLinkTrigger
      - name: Remove dynamodb-stream/goal-link-trigger
        run: cd dynamodb-stream/goal-link-trigger/remove/; GOOS=linux go build cmd/main.go; zip removeGoalLinkTrigger.zip main; ls;

      #- name: Remove GoalLinkTrigger Test
      #  run: cd dynamodb-stream/goal-link-trigger/remove/; go test -v ./...

      - name: Remove GoalLinkTrigger gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: removeGoalLinkTrigger
          zip_file: dynamodb-stream/goal-link-trigger/remove/removeGoalLinkTrigger.zip