name: Deploy Update InvestmentLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      # Update InvestmentLinkTrigger
      - name: Update dynamodb-stream/investment-link-trigger
        run: cd dynamodb-stream/investment-link-trigger/update/; GOOS=linux go build cmd/main.go; zip updateInvestmentLinkTrigger.zip main; ls;

      - name: Update InvestmentLinkTrigger Test
        run: cd dynamodb-stream/investment-link-trigger/update/; go test -v ./...

      - name: Update InvestmentLinkTrigger gobuild deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: updateInvestmentLinkTrigger
          zip_file: dynamodb-stream/investment-link-trigger/update/updateInvestmentLinkTrigger.zip