name: Deploy Update InvestmentLinkTrigger

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # Update InvestmentLinkTrigger
      - name: Update dynamodb-stream/investment-link-trigger
        run: cd dynamodb-stream/investment-link-trigger/update/; GOOS=linux go build cmd/main.go; zip updateInvestmentLinkTrigger.zip main; ls;

      - name: Update InvestmentLinkTrigger Test
        run: cd dynamodb-stream/investment-link-trigger/update/; go test -v ./...

      - name: Add updateInvestmentLinkTrigger gobuild deploy
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::064559090307:role/OIDCGithubRole
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Update lambda
        run: aws lambda update-function-code --function-name  updateInvestmentLinkTrigger --zip-file fileb://dynamodb-stream/investment-link-trigger/update/updateInvestmentLinkTrigger.zip